name: Build Demo and Deploy to Github Pages
permissions:
  contents: write
on:
  # release:
  #   types: [prereleased, released, published]
  # above does not work
  workflow_run:
    workflows: ["release.yml"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install and Build
        run: npm install && npm run build:web

      - name: Extra Files
        run: |
          # Switch to the generated directory
          cd dist

          # Set custom domain for GitHub Pages
          # echo "youdomain.com" > CNAME

          # Required to bypass Jekyll on GitHub Pages
          echo "" > .nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          single-commit: true
          branch: gh-pages
          clean: true
          folder: dist
